# Default values for hello-ring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: myRepo
  tag: myTag
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""
