apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-ring.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hello-ring.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hello-ring.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hello-ring.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: 
            - containerPort: 8080
