# Source: hello-ring/templates/ring.yaml
apiVersion: rings.microsoft.com/v1alpha1
kind: Ring
metadata:
  name: featureb
spec:
  # Deploy to environment
  deploy: true
  # Custom Claims
  claim: featureb
  entryPoints:
    # Source of traffic (eg: 80 or 443)
    - http
    - https
    - internal
  match: PathPrefix(`/`) && Headers(`x-ring`, `featureb`)
  selector:
    app.kubernetes.io/name: {{ include "hello-ring.name" . }}
